### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION error occurs after CLI tool is launched

### ISSUE THREAD

**Issue by theanine3D** [theanine3D/Blender-BAM-Exporter#1]
The addon currently launches the blend2bam tool successfully, passing on the appropriate parameters. However, with the newest Blender version at the time of writing this (3.5), the CLI tool appears to crash after being launched. The error is an "EXCEPTION_ACCESS_VIOLATION."

```
> Read blend: C:\Users\pv\Downloads\test.blend
> Error   : EXCEPTION_ACCESS_VIOLATION
> Address : 0x00007FF77486A3E0
> Module  : blender.exe
> Thread  : 000028ec
> Traceback (most recent call last):
>   File "C:\Users\pv\AppData\Roaming\Python\Python310\site-packages\blend2bam\cli.py", line 88, in convert
>     src2tmp.convert_single(srcfile, tmpfile.name)
>   File "C:\Users\pv\AppData\Roaming\Python\Python310\site-packages\blend2bam\blend2gltf\__init__.py", line 47, in convert_single
>     self.convert_batch(srcroot, dstdir, files)
>   File "C:\Users\pv\AppData\Roaming\Python\Python310\site-packages\blend2bam\blend2gltf\__init__.py", line 62, in convert_batch
>     blenderutils.run_blender_script(self.script_file, args, blenderdir=blenderdir)
>   File "C:\Users\pv\AppData\Roaming\Python\Python310\site-packages\blend2bam\blenderutils.py", line 29, in run_blender_script
>     run_blender(
>   File "C:\Users\pv\AppData\Roaming\Python\Python310\site-packages\blend2bam\blenderutils.py", line 25, in run_blender
>     subprocess.check_call(binpath + ['--background'] + args, stdout=None)#subprocess.DEVNULL)
>   File "C:\ProgramData\anaconda3\lib\subprocess.py", line 369, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['C:\\Program Files\\Blender Foundation\\Blender 3.5\\blender.exe', '--background', '-P', 'C:\\Users\\pv\\AppData\\Roaming\\Python\\Python310\\site-packages\\blend2bam\\blend2gltf\\blender28_script.py', '--', 'C:\\Users\\pv\\AppData\\Local\\Temp\\tmpnxe7iwsr', 'C:\\Users\\pv\\Downloads', 'C:\\Users\\pv\\AppData\\Local\\Temp', 'C:\\Users\\pv\\Downloads\\test.blend']' returned non-zero exit status 11.
> 
```

The addon installs and registers correctly in Blender 2.8 and does not produce any errors after attempting an export. However, no BAM file is actually created, so it seems to have issues even in 2.8 as well.

Note that the exception error is being produced by the CLI tool's code, not the addon's, so this might not be an issue with the addon itself.

**Comment by theanine3D** [comment]
Issue appears to be only occurring on my own local machine. Others have reported running the exporter without this issue.
